# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/VC707/top_enps/top_enps/top_enps.srcs/sources_1/ip/ila_top_enps/ila_top_enps.xci
# IP: The module: 'ila_top_enps' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/VC707/top_enps/top_enps/top_enps.srcs/sources_1/ip/ila_top_enps/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_top_enps'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/VC707/top_enps/top_enps/top_enps.srcs/sources_1/ip/ila_top_enps/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_top_enps'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/VC707/top_enps/top_enps/top_enps.srcs/sources_1/ip/ila_top_enps/ila_top_enps_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_top_enps'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/VC707/top_enps/top_enps/top_enps.srcs/sources_1/ip/ila_top_enps/ila_top_enps.xci
# IP: The module: 'ila_top_enps' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/VC707/top_enps/top_enps/top_enps.srcs/sources_1/ip/ila_top_enps/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_top_enps'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/VC707/top_enps/top_enps/top_enps.srcs/sources_1/ip/ila_top_enps/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_top_enps'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/VC707/top_enps/top_enps/top_enps.srcs/sources_1/ip/ila_top_enps/ila_top_enps_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_top_enps'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
